prettyPrint: true
openAPI:
  info:
    title: Arrowhead Authorization Core System API
    description: 'This page shows the REST interfaces offered by the Authorization Core System.'
    contact:
      url: https://github.com/arrowhead-f