prettyPrint: true
openAPI:
  info:
    title: Arrowhead Service Registry Core System API
    description: 'This page shows the REST interfaces offered by the Service Registry Core System.'
    contact:
      url: https://github.com/arrowhead-f