prettyPrint: true
openAPI:
  info:
    title: Arrowhead Event Handler Core System API
    description: 'This page shows the REST interfaces offered by the Event Handler Core System.'
    contact:
      url: https://github.com/arrowhead-f