prettyPrint: true
openAPI:
  info:
    title: Arrowhead QoS Core System API
    description: 'This page shows the REST interfaces offered by the QoS Core System.'
    contact:
      url: https://github.com/arrowhead-f