prettyPrint: true
openAPI:
  info:
    title: Arrowhead Gatekeeper Core System API
    description: 'This page shows the REST interfaces offered by the Gatekeeper Core System.'
    contact:
      url: https://github.com/arrowhead-f